#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Ho tro Webp"
echo "/-----------------------------------------------------------------------/"
echo

if [[ ! -f "/etc/nginx/conf.d/webp-mappings.conf" ]]; then
cat > "/etc/nginx/conf.d/webp-mappings.conf" <<END
map \$http_accept \$webp_suffix {
default ""; 
"~*webp" ".webp"; 
}
END
fi

get_choose_domain

if [[ -f "$path/nginx-webp.conf" ]]; then
read -p "Domain da cau hinh Webp. Ban co muon xoa? (y/n) " confirm
rm -f "$path/nginx-webp.conf"
echo "Da xoa Webp cua $domain"

else



cat > "$path/nginx-webp.conf" <<END
location ~* ^(/wp-content/.+).(png|jpe?g)$ {
set \$base \$1;
set \$webp_uri \$base\$webp_suffix;
set \$webp_old_uri \$base.\$2\$webp_suffix;
set \$root "${path}";
root \$root;
add_header Vary Accept;
if ( !-f \$root\$webp_uri ) {
add_header X_WebP_GP_Miss \$root\$webp_uri;
}
try_files \$webp_uri \$webp_old_uri \$uri =404;
}
END
nginx -t && service nginx restart
echo "Da thiet lap Webp cho $domain"

fi


action_wp_manager