#!/bin/bash
echo
echo "========================================================================="
echo "Cap nhat he thong"
echo "========================================================================="
echo "Huong dan: https://larvps.com/pages/documentation/all#section-23"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Kiem tra phien ban LarVPS"
    "Cap nhat LarVPS"
    "Cap nhat he thong Linux"
    "Cap nhat Rclone"
    # "Cap nhat Certbot"
    )
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/larvps_update/check_version'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/larvps_update/update_larvps'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/larvps_update/update_system'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/larvps_update/update_rclone'
            ;;
        # "${options[4]}")
        #     '/etc/larvps/menu/action/larvps_update/update_certbot'
        #     ;;
        *) larvps;;
    esac
done

