#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo
echo "==//====================================================================="
echo "29. Transfer website"
echo "/-----------------------------------------------------------------------/"
echo
cd

mkdir -p /usr/share/nginx/larvps/transfer

echo "Chon website ban muon Transfer:"
echo
get_choose_domain

DOMAIN=${domain}

PHP_VERSION="7.4"
USERNAME=$(get_user ${DOMAIN})
DATE=$(date +"%Y-%m-%d-%Hh")
FILE=${DATE}_${DOMAIN}.tar.gz

PATH_TRANSFER_FILE="/usr/share/nginx/larvps/transfer/${FILE}"
PATH_PUBLIC="/home/${USERNAME}/${DOMAIN}/public_html"


PATH_DATABASE="${PATH_PUBLIC}/database.sql.gz"
PATH_ENV="${PATH_PUBLIC}/.env"
PATH_WP_CONFIG="${PATH_PUBLIC}/wp-config.php"

DOWNLOAD=http://${ip}:${port_admin}/transfer/${FILE}
PATH_LETS="/root/.acme.sh/${DOMAIN}"
PATH_NGINX="/etc/nginx/conf.d/${DOMAIN}.conf"


mkdir -p "${PATH_PUBLIC}/.backup"
PATH_BACKUP_INCLUDE="${PATH_PUBLIC}/.backup"

#check ma nguon wp
if [[ -f ${PATH_WP_CONFIG} ]]; then
sed -i "s/\"/\'/g" ${PATH_WP_CONFIG}
DB_NAME=$(cat ${PATH_WP_CONFIG} | grep DB_NAME | cut -f4 -d"'" | xargs)
DB_USERNAME=$(cat ${PATH_WP_CONFIG} | grep DB_USER | cut -f4 -d"'" | xargs)
DB_PASSWORD=$(cat ${PATH_WP_CONFIG} | grep DB_PASSWORD | cut -f4 -d"'" | xargs)
fi

#check ma nguon laravel
if [[ -f ${PATH_ENV} ]]; then
DB_NAME=$(cat ${PATH_ENV} | grep DB_DATABASE | cut -f2 -d"=" | xargs)
DB_USERNAME=$(cat ${PATH_ENV} | grep DB_USERNAME | cut -f2 -d"=" | xargs)
DB_PASSWORD=$(cat ${PATH_ENV} | grep DB_PASSWORD | cut -f2 -d"=" | xargs)
fi

#backup option
rm -rf ${PATH_BACKUP_INCLUDE}
mkdir -p ${PATH_BACKUP_INCLUDE}/lets

cp -r ${PATH_LETS} "${PATH_BACKUP_INCLUDE}/lets"
if [[ -f ${PATH_LETS} ]]; then
cp -r ${PATH_NGINX} "${PATH_BACKUP_INCLUDE}/nginx"
fi

# backup database
if [[ ${DB_NAME} ]]; then
echo
echo "------------------------------------------"
echo "[${DOMAIN}]"
mysqldump -u ${DB_USERNAME} -p${DB_PASSWORD} ${DB_NAME} | gzip > ${PATH_DATABASE}
if [ "$?" -eq 0 ]; then
    echo -e "${CYAN}DATABASE:${END_COLOR} ${DB_NAME}"
    FILE_SIZE_DB=`du -h ${PATH_DATABASE} | cut -f1`
else
    echo "${CYAN}ERROR:${END_COLOR} Database"
fi

fi


echo "Dang tien hanh backup du lieu, vui long doi..."
cd /
tar fcz "${PATH_TRANSFER_FILE}" --absolute-names ${PATH_PUBLIC}
FILE_SIZE=`du -h ${PATH_TRANSFER_FILE} | cut -f1`
echo "-------------------------------------------------------------------------"
echo -e "${BLUE}INFO:${END_COLOR}"
echo "Size          : ${FILE_SIZE}"
echo "Database      : ${FILE_SIZE_DB}"
echo "Archive       : ${PATH_TRANSFER_FILE}"
echo "Delete        : rm -f ${PATH_TRANSFER_FILE}"
echo "Download      : ${DOWNLOAD}"
echo "Transfer       : transfer ${DOMAIN} admin ${ad_password}" ${DOWNLOAD} ${FILE}
echo "Auth User     : admin"
echo "Auth Password : ${ad_password}"
echo "-------------------------------------------------------------------------"
echo