#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions

P1=${1}
P2=${2}
P3=${3}
P4=${4}
P5=${5}

DOMAIN=${P1}
USERNAME=${P2}
PASSWORD=${P3}
URL=${P4}
FILE=${P5}

mkdir -p /usr/share/nginx/larvps/transfer

mkdir -p /usr/share/nginx/larvps/transfer/${FILE}
cd /usr/share/nginx/larvps/transfer
wget --http-user=${USERNAME} --http-password=${PASSWORD} ${URL} 
# restore ${DOMAIN} ${FILE} local