#!/bin/bash
dnf install epel-release -y
dnf upgrade -y
yum install snapd -y
systemctl enable --now snapd.socket
rm -f /var/lib/snapd/snap 
ln -s /var/lib/snapd/snap /snap
snap install core; snap refresh core
snap install --classic certbot
rm -f /usr/bin/certbot
ln -s /snap/bin/certbot /usr/bin/certbot

. /etc/larvps/menu/larvps_update