#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly Let's Encrypt > Test SSL"
echo "-------------------------------------------------------------------------"
echo "Huong dan: "
echo "/-----------------------------------------------------------------------/"
echo

if [[ ! -f "/etc/nginx/ssl/dhparam.pem" ]]; then

read -p "Nhap Email chinh cua ban (chinh xac): " email
if [[ ${email} ]]; then
wget -O -  https://get.acme.sh | sh -s email="${email}"
source  ~/.bashrc

mkdir -p /etc/nginx/ssl
openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048

echo "Da cai dat ACME."

cat > "/etc/nginx/ssl_config.conf" <<END
ssl_session_cache shared:SSL_LET:10m;
ssl_session_timeout  10m;
ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
ssl_ecdh_curve secp384r1;
ssl_prefer_server_ciphers on;
ssl_session_tickets off;
resolver 8.8.8.8 valid=300s;
resolver_timeout 5s;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;
END

fi

fi

echo "Chon domain:"
echo
get_choose_domain

if [[ ! -f /etc/nginx/conf.d/${domain}.conf ]]; then
clear
echo "Khong tim thay file config /etc/nginx/conf.d/${domain}.conf"
sleep 2
action_lets_encrypt
fi

is_subdomain ${domain}

if [[  "${IS_SUBDOMAIN}" = "n" ]]; then
	/root/.acme.sh/acme.sh --issue -d ${domain} -d www.${domain} --webroot /usr/share/nginx/html --test
else
	/root/.acme.sh/acme.sh --issue -d ${domain} --webroot /usr/share/nginx/html --test
fi

action_lets_encrypt